// WARNING: this file was autogenerated by LUnit. Remove this line or move this file to prevent this file's contents from being overwritten.

using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using LCore.Extensions;
using LCore.LUnit;
using LCore.LUnit.Markdown;
using Xunit;
using Xunit.Abstractions;

namespace LUnit_Tests.LCore.LUnit.Markdown
    {
    /*
    Covering class: LCore.LUnit.Markdown.MarkdownGenerator
    
    LUnit has Autogenerated 1 method stubs:
    */
    public partial class MarkdownGeneratorTester : XUnitOutputTester, IDisposable
        {
        public MarkdownGeneratorTester([NotNull] ITestOutputHelper Output) : base(Output) { }

        public void Dispose() { }

        [Fact]
        [Trait(Traits.TargetMember, nameof(LCore) + "." + nameof(global::LCore.LUnit) + "." + nameof(global::LCore.LUnit.Markdown) + "." + nameof(MarkdownGenerator) + "." + nameof(MarkdownGenerator.Generate) + "(Boolean)")]
        public void Generate()
            {
            var Gen = new LUnitMarkdownGenerator();

            Gen.Generate(true);

            List<GitHubMarkdown> Markdown = Gen.GetAllMarkdown();

            List<string> Paths = Markdown.Convert(MD => MD?.FilePath);

            Paths.Each(this._Output.WriteLine);
            }

        }
    }
